
#ifndef _ESTADOS_TRANSLATOR_H_
#define _ESTADOS_TRANSLATOR_H_

namespace Quorion {

	enum Estados
	{
		// Conf Datos del Cajero
		EDO_CONF_DATOS_DEL_CAJERO,

		// Conf Formas de Pago
		EDO_CONF_NOMBRES_FORMAS_DE_PAGO,

		// Conf Hora
		EDO_CONF_HORA,

		// Conf Fecha
		EDO_CONF_FECHA,

		// Conf Alícuotas del IVA
		EDO_CONF_DEL_IVA,
		EDO_CONF_DEL_IVA_MEMORIA_FISCAL,

		// Conf Encabezado
		EDO_CONF_ENCABEZADO,

		// Conf Pie de Factura
		EDO_CONF_PIE_DE_FACTURA,

		// Cajero Inicio
		EDO_CAJERO_INICIO,

		// Cajero Fin
		EDO_CAJERO_FIN,

		// Datos de Cliente
		EDO_DATOS_CLIENTE,
		EDO_SM_FACTURA,
		EDO_SM_NOTA_DE_CREDITO,
		EDO_DESCRIPCION_PRODUCTO,
		
		// Factura
		EDO_INICIO,
		EDO_FIN,
		EDO_INVALIDO,
		EDO_FACT_REGISTRO_PRODUCTO,
		EDO_FACT_DESCRIPCION_PRODUCTO,
		EDO_FACT_CORRECCION,
		EDO_FACT_SUBTOTAL,
		EDO_FACT_RECARGO_O_DESCUENTO,
		EDO_FACT_ANULACION_ITEM,
		EDO_FACT_ANULACION_FACTURA,
		EDO_FACT_PAGO_DIRECTO,
		EDO_FACT_PAGO_PARCIAL,
		EDO_FACT_CODIGO_DE_BARRA,
		EDO_GENERAR_FACTURA,

		// Nota de Crédito
		EDO_NC_REGISTRO_PRODUCTO,
		EDO_NC_DESCRIPCION_PRODUCTO,
		EDO_NC_SUBTOTAL,
		EDO_NC_RECARGO_O_DESCUENTO,
		EDO_NC_ANULACION_ITEM,
		EDO_NC_CIERRE_DEVOLUCION,
		EDO_GENERAR_NOTA_CREDITO,

		// DNF Texto
		EDO_DNF_TEXTO,

		// DNF Apertura Gaveta
		EDO_DNF_APERTURA_GAVETA,
		
		// DNF PO y RA
		EDO_DNF_PO_RA,

		// DNF Imprimir Valor de Conf
		EDO_DNF_PRINT_VALOR_CONF,

		// DNF Codigo de Barra
		EDO_DNF_CODIGO_BARRA,

		// Display Mensaje
		EDO_DISPLAY_MENSAJE,

		// Status
		EDO_STATUS,

		// Reportes de Cierre
		EDO_REPORTE_X,
		EDO_REPORTE_Z,

		// Reportes de Memoria Fiscal
		EDO_REPORTE_MFISCAL_FECHA,
		EDO_REPORTE_MFISCAL_NUMERO,

		// Reimpresión de Documentos
		EDO_REIMPRESION_DOC_FECHA,
		EDO_REIMPRESION_DOC_NUMERO,

		// Impresion de Estado de Memoeria de Auditoria
		EDO_PRINT_EDO_MEMORIA_AUDITORIA,

		// Inicial
		EDO_SM_CONF_DATOS_CAJERO,
		EDO_SM_CONF_NOMBRES_FORMAS_DE_PAGO,
		EDO_SM_CONF_HORA,
		EDO_SM_CONF_FECHA,
		EDO_SM_CONF_DEL_IVA,
		EDO_SM_CONF_ENCABEZADO,
		EDO_SM_CONF_PIE_DE_FACTURA,
		EDO_SM_CAJERO_INICIO,
		EDO_SM_CAJERO_FIN,
		EDO_SM_DATOS_CLIENTE,
		EDO_SM_NC_REGISTRO_PRODUCTO,
		EDO_SM_DNF_TEXTO,
		EDO_SM_DNF_APERTURA_GAVETA,
		EDO_SM_DNF_PO_RA,
		EDO_SM_DNF_VALOR_CONF,
		EDO_SM_DNF_CODIGO_BARRA,
		EDO_SM_DISPLAY_MENSAJE,
		EDO_SM_STATUS,
		EDO_SM_REPORTE_X,
		EDO_SM_REPORTE_Z,
		EDO_SM_MFISCAL_FECHA,
		EDO_SM_MFISCAL_NUMERO,
		EDO_SM_REIMPRESION_FECHA,
		EDO_SM_REIMPRESION_NUMERO,
		EDO_SM_PRINT_EDO_MAUDITORIA
		
	};

	enum Eventos
	{
		// Conf Datos del Cajero
		TKN_CONF_DATOS_DEL_CAJERO,

		// Conf Formas de Pago
		TKN_CONF_NOMBRES_FORMAS_DE_PAGO,

		// Conf Hora
		TKN_CONF_HORA,

		// Conf Fecha
		TKN_CONF_FECHA,

		// Conf Alícuotas del IVA
		TKN_CONF_DEL_IVA,
		TKN_CONF_DEL_IVA_MEMORIA_FISCAL,
		EVT_FIN_CONF_DEL_IVA,

		// Conf Encabezado
		TKN_CONF_ENCABEZADO,

		// Conf Pie de Factura
		TKN_CONF_PIE_DE_FACTURA,

		// Cajero Inicio
		TKN_CAJERO_INICIO,

		// Cajero Fin
		TKN_CAJERO_FIN,

		// Datos de Cliente
		TKN_DATOS_CLIENTE,
		EVT_FINALIZADO,
		
		// Factura
		EVT_NEUTRO,
		TKN_FACT_REGISTRO_PRODUCTO,
		TKN_FACT_DESCRIPCION_PRODUCTO,
		TKN_FACT_CORRECCION,
		TKN_FACT_SUBTOTAL,
		TKN_FACT_RECARGO_O_DESCUENTO,
		TKN_FACT_ANULACION_ITEM,
		TKN_FACT_ANULACION_FACTURA,
		TKN_FACT_PAGO_DIRECTO,
		TKN_FACT_PAGO_PARCIAL,
		TKN_FACT_CODIGO_DE_BARRA,
		EVT_MONTO_TOTAL_ALCANZADO,
		
		// Nota de Crédito
		TKN_NC_REGISTRO_PRODUCTO,
		TKN_NC_ANULACION_ITEM,
		TKN_NC_CIERRE_DEVOLUCION,
	//	EVT_NC_PAGO_PARCIAL,
		EVT_NC_FIN_CIERRE,

		// DNF Texto
		TKN_DNF_TEXTO,

		// DNF Apertura Gaveta
		TKN_DNF_APERTURA_GAVETA,
		
		// DNF PO y RA
		TKN_DNF_PO_RA,
		TKN_DNF_FINALIZAR_PO_RA,

		// DNF Imprimir Valor de Conf
		TKN_DNF_PRINT_VALOR_CONF,

		// Display Mensaje
		TKN_DISPLAY_MENSAJE,

		// Status
		TKN_STATUS,

		// Reportes de Cierre
		TKN_REPORTE_X,
		TKN_REPORTE_Z,

		// Reportes de Memoria Fiscal
		TKN_REPORTE_MFISCAL_FECHA,
		TKN_REPORTE_MFISCAL_NUMERO,

		// Reimpresión de Documentos
		TKN_REIMPRESION_DOC_POR_FECHA,
		TKN_REIMPRESION_DOC_POR_NUMERO,

		// Impresion de Estado de Memoeria de Auditoria
		TKN_PRINT_EDO_MEMORIA_AUDITORIA,

		TKN_OTRO_1,
		TKN_OTRO_2,
		TKN_OTRO_3,
		TKN_OTRO_4,
		TKN_OTRO_5,

		EVT_ERROR

	};

	enum Accion
	{
		ACC_IN,
		ACC_OUT
	};

} // namespace Quorion

#endif // _ESTADOS_TRANSLATOR_H_